# Generated by Django 4.2.5 on 2023-09-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='counter',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
